services:
  api:
    tty: true
    container_name: remitly-api-prod-1
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: ".env.prod"  
    depends_on:
      - database
    command: npm run start

  database:
    container_name: remitly-database-prod-1
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres-data-prod:
